// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn1g1BoQD2-XGcQxutSGqFKwuHfKIljA8',
    appId: '1:704109695137:web:4ef335cb97a627d0b7e0e0',
    messagingSenderId: '704109695137',
    projectId: 'bus-app-e2938',
    authDomain: 'bus-app-e2938.firebaseapp.com',
    storageBucket: 'bus-app-e2938.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVp8PMOyWsOrKC5JiZzPB7FgxnB9Q0ppM',
    appId: '1:704109695137:android:a33cdd6211891b1cb7e0e0',
    messagingSenderId: '704109695137',
    projectId: 'bus-app-e2938',
    storageBucket: 'bus-app-e2938.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtWgdFxA7BhWquHipJImYIozeLV0DUIBM',
    appId: '1:704109695137:ios:b6dd8a7ca3ff0ee4b7e0e0',
    messagingSenderId: '704109695137',
    projectId: 'bus-app-e2938',
    storageBucket: 'bus-app-e2938.firebasestorage.app',
    iosBundleId: 'com.example.busapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtWgdFxA7BhWquHipJImYIozeLV0DUIBM',
    appId: '1:704109695137:ios:b6dd8a7ca3ff0ee4b7e0e0',
    messagingSenderId: '704109695137',
    projectId: 'bus-app-e2938',
    storageBucket: 'bus-app-e2938.firebasestorage.app',
    iosBundleId: 'com.example.busapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn1g1BoQD2-XGcQxutSGqFKwuHfKIljA8',
    appId: '1:704109695137:web:d52b15ae73d8dc21b7e0e0',
    messagingSenderId: '704109695137',
    projectId: 'bus-app-e2938',
    authDomain: 'bus-app-e2938.firebaseapp.com',
    storageBucket: 'bus-app-e2938.firebasestorage.app',
  );
}
